### ISSUE TITLE
Dropdown onToggle is called 2 times. 

### ISSUE THREAD

**Issue by AurimasGaidys** [SimplrJS/simplr-dropdown#13]
Function onToggle is called few times. Fixed by adding event.stopPropagation to onClick function. Probably should be added by default.

**Comment by MartynasZilinskas** [comment]
Fixed https://github.com/SimplrJS/simplr-dropdown/commit/9ddde259ae63e16e6f40fede245a494573532667.

**Comment by MartynasZilinskas** [comment]
This was actually not an issue. 
I fixed the real problem: https://github.com/SimplrJS/simplr-dropdown/pull/14.
